### ISSUE TITLE
instructions not clear

### ISSUE THREAD

**Issue by genemiller** [techyworm10/firebase-unity-sdk-editor-python-fix#1]
Thank you for this fix.

But I was not sure what these instructions mean: "Replace the files located in `Firebase.Editor` with those in your Unity project's `./Assets/Firebase/Editor` folder."

I took a guess and replaced the files in my `./Assets/Firebase/Editor` folder with those in your `Firebase.Editor` folder (opposite to the above instructions). Is this what you had in mind?

Fortunately, this replacement fixed the problem:
```
Internal build system error. Backend exited with code 2.
tundra: error: Unexpected stdin
```
Notes:
- The files I replaced in my `.Editor` folder included `generate_xml_from_google_services_json.py` and `network_request.py`.
- My `./Assets/Firebase/Firebase.Editor` folder contains `Firebase.Editor.pdb` and `Firebase.Editor.dll.mdb` (also in your `Firebase.Editor` folder)

Prior to this replacement, I was getting two python related errors. After this replacement, I started getting these two errors:
```
Generation of the Firebase Android resource file google-services.xml from Assets/StreamingAssets/GoogleService-Info.plist failed.
Generation of the Firebase Android resource file google-services.xml from Assets/StreamingAssets/google-services.json failed.
```
My section of the code does not depend on Firebase and it is working fine. I don't know how other parts of the code depend on Firebase.

Do you think I should be concerned about how I applied the fix?

**Comment by techyworm10** [comment]
You need to copy the files, not replace the entire content (sorry if it wasn't clear).
I've updated the instructions, and I hope it's more clear now.
You might need to restart Unity if it was open while replacing the files.

**Comment by genemiller** [comment]
Great work, techyworm10!
All errors are gone and the 'tundra' problem remains fixed.
